defaults:
  - _self_
  # - model: ElderNet
  - model: TremorNet
  - augmentation: all
  - dataloader: ten_sec_no_overlap

model:
  ssl_method: mtl
  # num_epochs : 5
  num_epochs: 30
  # num_epochs: 2
  lr :  1e-4
  batch_size : 100
  # patience: 5
  patience: 5
  multiclass: True
  rebalance: False
  classes_to_remove: [1] # only matters in case of binary classification
  equal_class_weights: True
  use_groups: False

data:
  # data_root: \parsing_output
  # log_path: \logs
  data_root: ..\parsing_output
  log_path: ..\logs
  dense_labeling: False