defaults:
  - _self_
  - model: resnet_plus
  - data: RUSH
  - augmentation: all
  - task: all
  - dataloader: ten_sec_no_overlap


model:
  ssl_method : mtl
  warm_up_step: 5
  lr_scale: true

data:
  data_root: N:\Gait-Neurodynamics by Names\Yonatan\SSL\ssl_gait_detection\data\RUSH\

